### ISSUE TITLE
Use name `mycoai` for pypi package?

### ISSUE THREAD

**Issue by CunliangGeng** [MycoAI/MycoAI#1]
The current name of [pypi package](https://pypi.org/project/mycoai-its/) is `mycoai-its`. There might be special reasons to add `-its` after `mycoai`. If not, It's better to keep the names of your github repo and pypi package the same.

**Comment by luukromeijn** [comment]
We would very much prefer `mycoai` over `mycoai-its`. However, PyPi finds the first too similar to an already existing package name.

**Comment by CunliangGeng** [comment]
@luukromeijn  Are you sure? This is what I get when searching `mycoai` on pypi, only one hit:
![image](https://github.com/user-attachments/assets/2feffb80-8b05-414d-a464-0168dbd8e40e)

**Comment by luukromeijn** [comment]
Yeah, I am pretty sure. It could be that the situation changed after a few months of course. We can try again once we publish the new version on PyPi (Will be soon, but right now I'm on vacation :) ).
